[dependencies]
base = "0.12.1"
vector = "0.4.0"
map = "9.0.1"
swbstable = "1.1.1"
stableheapbtreemap = "1.5.0"
devefi-icp-ledger = "../devefi_icp_ledger/"
devefi-icrc-ledger = "../devefi_icrc_ledger/"
